# This file is generated by the caffeinum release workflow. DO NOT EDIT.
cask "caffeinum" do
  version "0.1.0"
  sha256 "de45be22d9a144f85a004e5567bfd7a275fd6064ebbe75bcfa789af160027bb4"

  url "https://github.com/vojtechmares/caffeinum/releases/download/v#{version}/Caffeinum-#{version}-arm64.zip"
  name "Caffeinum"
  desc "Menu bar app that prevents sleep and sets the daily wake/sleep schedule"
  homepage "https://github.com/vojtechmares/caffeinum"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :ventura

  app "Caffeinum.app"

  # Homebrew 6 removed "brew install --cask --no-quarantine", so the cask has to
  # clear the flag itself. Caffeinum is ad-hoc signed but not notarised, and
  # Gatekeeper will not launch a quarantined bundle it cannot verify. Failing
  # here would abort the install after the app is already in place, and a
  # Gatekeeper prompt is the better of those two outcomes.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-d", "-r", "com.apple.quarantine", "#{appdir}/Caffeinum.app"],
                   must_succeed: false
  end

  uninstall quit: "cz.mares.caffeinum"

  zap trash: [
    "~/Library/Caches/cz.mares.caffeinum",
    "~/Library/Preferences/cz.mares.caffeinum.plist",
  ]

  caveats <<~EOS
    Caffeinum is ad-hoc signed but not notarised. This cask clears the
    com.apple.quarantine flag on Caffeinum.app after installing it, which is
    what lets it launch without Gatekeeper refusing to verify it.
  EOS
end
