# typed: false
# frozen_string_literal: true

# This file is generated by the coding-owl release workflow. DO NOT EDIT.
cask "coding-owl-desktop" do
  version "0.1.0"
  sha256 "099a0473cf9b145adbcb3dd5af81db082b24068f4233948ae5a8ada3da986250"

  url "https://github.com/vojtechmares/coding-owl/releases/download/v#{version}/CodingOwl-#{version}-arm64.zip"
  name "Coding Owl"
  desc "Runs coding agents on your machine while it is otherwise idle"
  homepage "https://github.com/vojtechmares/coding-owl"

  livecheck do
    url :url
    strategy :github_latest
  end

  # In the order brew style wants them, which is not the order they read in.
  depends_on arch: :arm64
  # The app is a view over the daemon the formula ships, so the two are one
  # installation and there is exactly one daemon per machine (ADR-0010).
  depends_on formula: "vojtechmares/tap/coding-owl"
  depends_on macos: :ventura

  app "Coding Owl.app"

  # Homebrew 6 removed "brew install --cask --no-quarantine", so the cask has to
  # clear the flag itself. Coding Owl is ad-hoc signed but not notarised, and
  # Gatekeeper will not launch a quarantined bundle it cannot verify. Failing
  # here would abort the install after the app is already in place, and a
  # Gatekeeper prompt is the better of those two outcomes.
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-d", "-r", "com.apple.quarantine", "{{appdir}}/Coding Owl.app"],
        must_succeed: false
  end

  uninstall quit: "dev.codingowl.desktop"

  # The app keeps nothing of its own: the daemon holds the database, the
  # credentials and the configuration, and "brew uninstall coding-owl" is what
  # takes those away.
  zap trash: [
    "~/Library/Caches/dev.codingowl.desktop",
    "~/Library/Preferences/dev.codingowl.desktop.plist",
    "~/Library/Saved Application State/dev.codingowl.desktop.savedState",
    "~/Library/WebKit/dev.codingowl.desktop",
  ]

  caveats <<~EOS
    Coding Owl is ad-hoc signed but not notarised. This cask clears the
    com.apple.quarantine flag on Coding Owl.app after installing it, which is
    what lets it launch without Gatekeeper refusing to verify it.

    The app is a view: the daemon does the work, and it comes from the
    coding-owl formula this cask depends on. Start it with

      brew services start coding-owl

    Everything Owl holds - its database, its configuration and its credentials -
    belongs to the daemon, so "brew uninstall --zap --cask coding-owl-desktop"
    removes the app and leaves those alone.
  EOS
end
