# This file is generated by the reviewdeck release workflow. DO NOT EDIT.
cask "reviewdeck" do
  version "0.4.0"
  sha256 "6ba5dd5685cbe83e23c911516c83809fc28e4bbfeac156d9a3e1b9ffd30111e4"

  url "https://github.com/vojtechmares/reviewdeck/releases/download/v#{version}/Reviewdeck-#{version}-arm64.zip"
  name "Reviewdeck"
  desc "Collects the code reviews waiting on you across every Git host"
  homepage "https://github.com/vojtechmares/reviewdeck"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on arch: :arm64
  depends_on macos: :monterey

  app "Reviewdeck.app"

  # Homebrew 6 removed "brew install --cask --no-quarantine", so the cask has to
  # clear the flag itself. Reviewdeck is ad-hoc signed but not notarised, and
  # Gatekeeper will not launch a quarantined bundle it cannot verify. Failing
  # here would abort the install after the app is already in place, and a
  # Gatekeeper prompt is the better of those two outcomes.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-d", "-r", "com.apple.quarantine", "#{appdir}/Reviewdeck.app"],
                   must_succeed: false
  end

  uninstall quit: "cz.mares.reviewdeck"

  # Electron names the data directory after package.json's "name" when running
  # from source and after the bundle when packaged, so both spellings are here.
  zap trash: [
    "~/Library/Application Support/Reviewdeck",
    "~/Library/Application Support/reviewdeck",
    "~/Library/Caches/cz.mares.reviewdeck",
    "~/Library/Preferences/cz.mares.reviewdeck.plist",
    "~/Library/Saved Application State/cz.mares.reviewdeck.savedState",
  ]

  caveats <<~EOS
    Reviewdeck is ad-hoc signed but not notarised. This cask clears the
    com.apple.quarantine flag on Reviewdeck.app after installing it, which is
    what lets it launch without Gatekeeper refusing to verify it.

    Access tokens are kept in the macOS Keychain via Electron's safeStorage;
    "brew uninstall --zap" removes the on-disk config but not the Keychain
    entry.
  EOS
end
