# typed: false
# frozen_string_literal: true

# This file is generated by the coding-owl release workflow. DO NOT EDIT.
class CodingOwl < Formula
  desc "Runs coding agents on your machine while it is otherwise idle"
  homepage "https://github.com/vojtechmares/coding-owl"
  url "https://github.com/vojtechmares/coding-owl/releases/download/v0.1.0/coding-owl_v0.1.0_darwin_arm64.tar.gz"
  version "0.1.0"
  sha256 "79e3754c416753026cf59c20c53d84d5d78fcc5e1d97ed40df71138dd96ec9b0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  # darwin/arm64 is the only platform the MVP releases for (ADR-0010).
  depends_on arch: :arm64
  depends_on :macos

  def install
    bin.install "owl"
  end

  # The daemon runs in the foreground under a supervisor and never daemonizes
  # itself (ADR-0002), so brew services is what keeps it running.
  service do
    run [opt_bin/"owl", "daemon", "run"]
    keep_alive true
    log_path var/"log/coding-owl.log"
    error_log_path var/"log/coding-owl.log"
    # Claude Code's own installer puts claude under ~/.local/bin, which the
    # standard service PATH does not hold; a daemon that cannot find the tool
    # cannot run anything. The daemon's own file can name the tool outright
    # with claudePath, for a tool that is somewhere else again.
    environment_variables PATH: "#{std_service_path_env}:#{Dir.home}/.local/bin"
  end

  def caveats
    <<~EOS
      Start the daemon and keep it running across logins:

        brew services start coding-owl

      It logs to #{var}/log/coding-owl.log. Check on it with:

        owl daemon status

      The service runs with a fixed PATH: Homebrew's, plus ~/.local/bin,
      where Claude Code's installer puts claude. If claude is somewhere
      else, name it in the daemon's own file and restart the service:

        claudePath: /path/to/claude
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/owl --version")
  end
end
