# This file was generated by GoReleaser. DO NOT EDIT.
class Statica < Formula
  desc "Simple CLI tool to deploy static websites to AWS S3 with Cloudflare DNS"
  homepage "https://github.com/vojtechmares/statica"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vojtechmares/statica/releases/download/v0.1.0/statica_v0.1.0_darwin_amd64.tar.gz"
    sha256 "cd0fd650dfff916a6e599b93b299dd14719c2c459912ab3ba59f9d8af07bf800"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/vojtechmares/statica/releases/download/v0.1.0/statica_v0.1.0_linux_amd64.tar.gz"
    sha256 "f063e521d750c669901701c6e425b42cbf199cd05f73804e29649e48de1c9152"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/vojtechmares/statica/releases/download/v0.1.0/statica_v0.1.0_linux_arm64.tar.gz"
    sha256 "b0c2d569124cdc66025250be8a83a36e39f326be4079545976a35336a0c166f2"
  end

  def install
    bin.install "statica"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/vojtechmares/statica#usage
  EOS
  end

  test do
    system "#{bin}/statica --version"
  end
end
