# This file was generated by GoReleaser. DO NOT EDIT.
class Statica < Formula
  desc "Simple CLI tool to deploy static websites to AWS S3 with Cloudflare DNS"
  homepage "https://github.com/vojtechmares/statica"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vojtechmares/statica/releases/download/v0.2.1/statica_v0.2.1_darwin_amd64.tar.gz"
    sha256 "88c84fb716bfd648d3dfe1a54d557cc93fd6fd7b7e1238110350fb621ab90510"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/vojtechmares/statica/releases/download/v0.2.1/statica_v0.2.1_linux_amd64.tar.gz"
    sha256 "42e1e259061e09cd23d5f08837858691cdfd19dfaaf3a2c877008a154b221076"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/vojtechmares/statica/releases/download/v0.2.1/statica_v0.2.1_linux_arm64.tar.gz"
    sha256 "44abea5ec10363c318f250c47adc99b7f74e001042e8091a37fd569e07191818"
  end

  def install
    bin.install "statica"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/vojtechmares/statica#usage
  EOS
  end

  test do
    system "#{bin}/statica version"
  end
end
